routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\PagesController;
use App\Http\Controllers\Admin\UsersController;
use App\Http\Controllers\Admin\BlogController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/admin', function(){
    return view('admin.index');
})->middleware('admin');


Route::resource('/admin/pages', PagesController::class, ['except' => ['show']]);

Route::resource('/admin/users', UsersController::class, ['except' => ['show', 'create', 'store']]);

Route::resource('/admin/blog', BlogController::class, ['except' => ['show']]);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];


    public function pages(){
        return $this->hasMany(Page::class);
    }

    public function roles(){
        return $this->belongsToMany(Role::class);
    }

    public function hasAnyRole($roles){
        return null != $this->roles()->whereIn('name', $roles)->first();
    }

    public function hasRole($role){
        return null != $this->roles()->where('name', $role)->first();
    }

    public function isAdminOrEditor(){
        return $this->hasAnyRole(['admin','editor']);
    }

    public function posts(){
        return $this->hasMany(Post::class);
    }
}

app/Http/Controllers/Admin/UsersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\User;
use Auth;
use App\Models\Role;
use Illuminate\Http\Request;

class UsersController extends Controller
{

    public function __construct(){
        $this->middleware('admin');
        $this->middleware('can:manageUsers,App\Models\User');
    }    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        return view('admin.users.index')->with('model', User::paginate(1));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        //
        if(Auth::user()->id == $user->id){
            return redirect()->route('users.index')->with('status', 'You cannot edit yourself!');
        }
        return view('admin.users.edit', [
            'model' => $user,
            'roles' => Role::all()
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        //
        if(Auth::user()->id == $user->id){
            return redirect()->route('users.index')->with('status', 'You cannot edit yourself!');
        }
        
        $user->roles()->sync($request->roles);
        $user->fill($request->only('name', 'email'));
        $user->save();

        return redirect()->route('users.index')->with('status', "$user->name updated successfully");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        //
        if(Auth::user()->id == $user->id){
            return redirect()->route('users.index')->with('status', 'You cannot delete yourself!');
        }

        $user->delete();
        return redirect()->route('users.index');
    }
}

resources/views/admin/users/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <h1>Edit {{ $model->name }}</h1>

    <form action="{{ route('users.update', ['user' => $model->id]) }}" method="post">
        {{ method_field('PUT') }}
        {!! csrf_field() !!}

        @if (!$errors->isEmpty())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $message)
                    
                        <li>{{ $message }}</li>

                    @endforeach
                </ul>
            </div>
        @endif
        <div class="form-group">
            <label for="name">Name</label>
            <input type="text" class="form-control" id="name" name="name" value="{{ $model->name }}">
        </div>
        <div class="form-group">
            <label for="email">Email</label>
            <input type="text" class="form-control" id="email" name="email" value="{{ $model->email }}">
        </div>
        @foreach($roles as $role)
        <div class="checkbox">
            <label>
                <input type="checkbox" name="roles[]" value="{{ $role->id }}"
                {{ $model->hasRole($role->name) ? 'checked' : '' }} />
                {{ $role->name }}
            </label>
        </div>
        @endforeach
        <div class="form-group">
            <input type="submit" class="btn btn-default" value="Submit" />
        </div>
    
    </form>
    
</div>

@endsection

resources/views/admin/users/index.blade.php
@extends('layouts.app')

@section('content')

<div class="container">

    @if(session('status'))
        <div class="alert alert-info">{{ session('status') }}</div>
    @endif
    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Email</th>
                <th>Roles</th>
                <th>Actions</th>
            </tr>
        </thead>

        @foreach ($model as $user)
            <tr>
                <td>{{ $user->id }}</td>
                <td>
                    <a href="{{ route('users.edit',['user' => $user->id]) }}">{{ $user->name }}</a>
                </td>
                <td>{{ $user->email }}</td>
                <td>
                    {{ implode(', ', $user->roles()->get()->pluck('name')->toArray()) }}
                </td>
                <td>
                    <form action="{{ route('users.destroy', ['user' => $user->id]) }}" method="POST">
                        @csrf

                        @method('DELETE')

                        <button type="submit" class="btn btn-danger btn-block">Delete</button>
                    </form>
                </td>
            </tr>
        @endforeach

    </table>
    {{ $model->links() }}
</div>

@endsection