routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\PagesController;
use App\Http\Controllers\Admin\UsersController;
use App\Http\Controllers\Admin\BlogController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/admin', function(){
    return view('admin.index');
})->middleware('admin');


Route::resource('/admin/pages', PagesController::class, ['except' => ['show']]);

Route::resource('/admin/users', UsersController::class, ['except' => ['show', 'create', 'store']]);

Route::resource('/admin/blog', BlogController::class, ['except' => ['show']]);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;


    protected $fillable = ['title', 'slug', 'excerpt', 'body', 'published_at'];

    public function user(){
        return $this->belongsTo(User::class);
    }
}

resources/views/admin/posts/create.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <h1>Create New Post</h1>

    <form action="{{ route('posts.store') }}" method="post">
        @include('admin.posts.partials.fields')
    </form>
    
</div>

@endsection

resources/views/admin/posts/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <h1>Edit Post</h1>

    <form action="{{ route('posts.update', ['post' => $model->id]) }}" method="post">
        {{ method_field('PUT') }}
        @include('admin.posts.partials.fields')
    
    </form>
    
</div>

@endsection

resources/views/admin/posts/index.blade.php
@extends('layouts.app')

@section('content')

<div class="container">

    @if(session('status'))
        <div class="alert alert-info">{{ session('status') }}</div>
    @endif

    <a href="{{ route('blog.create') }}" class="btn btn-default">Create New Post</a>
    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Title</th>
                <th>Slug</th>
                <th>Author</th>
                <th>Published</th>
                <th>Actions</th>
            </tr>
        </thead>

        @foreach ($posts as $post)
            <tr>
                <td>{{ $post->id }}</td>
                <td>
                    <a href="{{ route('blog.edit',['blog' => $post->id]) }}">{{ $post->title }}</a>
                </td>
                <td>{{ $post->slug }}</td>
                <td>{{ $post->user()->first()->name }}</td>
                <td></td>
                <td>
                    <form action="{{ route('blog.destroy', ['blog' => $post->id]) }}" method="POST">
                        @csrf

                        @method('DELETE')

                        <button type="submit" class="btn btn-danger btn-block">Delete</button>
                    </form>
                </td>
            </tr>
        @endforeach

    </table>
    {{ $posts->links() }}
</div>

@endsection