routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\PagesController;
use App\Http\Controllers\Admin\UsersController;
use App\Http\Controllers\Admin\BlogController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/admin', function(){
    return view('admin.index');
})->middleware('admin');


Route::resource('/admin/pages', PagesController::class, ['except' => ['show']]);

Route::resource('/admin/users', UsersController::class, ['except' => ['show', 'create', 'store']]);

Route::resource('/admin/blog', BlogController::class, ['except' => ['show']]);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

resources/views/admin/pages/create.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <h1>Create New Page</h1>

    <form action="{{ route('pages.store') }}" method="post">
        @include('admin.pages.partials.fields')
    </form>
    
</div>

@endsection

resources/views/admin/pages/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <h1>Edit Page</h1>

    <form action="{{ route('pages.update', ['page' => $model->id]) }}" method="post">
        {{ method_field('PUT') }}
        @include('admin.pages.partials.fields')
    
    </form>
    
</div>

@endsection

resources/views/admin/pages/index.blade.php
@extends('layouts.app')

@section('content')

<div class="container">

    @if(session('status'))
        <div class="alert alert-info">{{ session('status') }}</div>
    @endif

    <a href="{{ route('pages.create') }}" class="btn btn-default">Create New Page</a>
    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Title</th>
                <th>URL</th>
                <th>Content</th>
                <th>Creator</th>
                <th>Actions</th>
            </tr>
        </thead>

        @foreach ($pages as $page)
            <tr>
                <td>{{ $page->id }}</td>
                <td>
                    <a href="{{ route('pages.edit',['page' => $page->id]) }}">{{ $page->title }}</a>
                </td>
                <td>{{ $page->url }}</td>
                <td>{{ $page->content }}</td>
                <td>{{ $page->user()->first()->name }}</td>
                <td>
                    <form action="{{ route('pages.destroy', ['page' => $page->id]) }}" method="POST">
                        @csrf

                        @method('DELETE')

                        <button type="submit" class="btn btn-danger btn-block">Delete</button>
                    </form>
                </td>
            </tr>
        @endforeach

    </table>
    {{ $pages->links() }}
</div>

@endsection